version: "3.8"
services:
    db:
        container_name: mysql
        build: ./db
        ###### image: 
        environment: 
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ###### MYSQL_DATABASE:
        volumes:
        -type: volume
        ###### source: 
        target: /var/lib/mysql
    nginx:
        image: nginx:latest
        ports:
            -target: 80
            published: 80
            protocol: tcp
        volumes:
        - type: bind     
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf

    frontend:
        container_name: frontend
        build: ./frontend
        ###### image:
        ports:
        - target: 5000
          published: 5000

    backend:
        container_name: backend
        build: ./backend
        ###### image:
        environment:
        DATABASE_URI: ${DATABASE_URI}
        depends_on:
            - db
        ports:
            - target: 5001
            - published: 5001