version: "3.8"
services:
    db:
        container_name: mysql
        build: ./database
        image: enixon/testdb
        environment: 
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          MYSQL_DATABASE: testdb
        volumes:
        - type: volume
          source: testdb
          target: /var/lib/mysql
    nginx:
        image: nginx:latest
        ports:
        - target: 80
          published: 80
          protocol: tcp
        volumes:
        - type: bind     
          source: ./nginx/nginx.conf
          target: /etc/nginx/nginx.conf

    frontend:
        container_name: frontend
        build: ./frontend
        image: enixon/frontend
        ports:
        - target: 5000
          published: 5000

    backend:
        container_name: backend
        build: ./backend
        image: enixon/backend
        ports:
        - target: 5001
          published: 5001

volumes:
  testdb: