- name: install Jenkins
  become: yes
  hosts: jenkins
  roles: 
  - docker
  - jenkins

- name: install Docker onto Production machine
  become: yes
  hosts: prod
  roles: 
  - docker

- name: install Docker onto Test machine
  become: yes
  hosts: test
  roles: 
  - docker