
- name: "generate key pair"
  openssh_keypair:
    path: ~/.ssh/ansible_id_rsa

- name: jenkins user
  user:
    name: jenkins
    shell: /bin/bash

- name: prerequisites
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common
    - git
    
    state: latest
    update_cache: true

- name: Install python3
  apt:
    pkg:
    - python3
    - python3-virtualenv
    - python3-dev
    - virtualenv
    state: present
    update_cache: true

- name: Install python-pip
  apt:
    pkg:
    - python3-pip
    - curl
    state: present
    update_cache: true 


- name: docker
  pip:
    name: docker

- name: json
  pip:
    name: jsondiff
- name: requests
  pip:
    name: requests
- name: yaml
  pip:
    name: pyyaml
- name: compose
  pip:
    name: docker-compose

- name: docker gpg key
  apt_key:
    url: "https://download.docker.com/linux/debian/gpg"
    state: present

- name: docker apt repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian stretch stable"
    state: present

- name: docker install
  apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    state: latest
    update_cache: true

- name: docker service
  service:
    name: docker
    state: started

- name: Add jenkins user to docker group
  user:
    name: jenkins
    comment: docker-jenk
    group: docker

- name: ssh folder
  file:
    path: /home/ubuntu/.ssh
    state: directory
    mode: "0700"
    owner: jenkins
    group: jenkins 

- name: install public key
  copy:
    src: ~/.ssh/ansible_id_rsa.pub
    dest: /home/ubuntu/.ssh/authorized_keys
    owner: jenkins
    group: jenkins
    mode: u=rw,g=,o=